CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    passwordHash VARCHAR(255) NOT NULL,
    token VARCHAR(50) NOT NULL UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tokens (
    userid INT NOT NULL PRIMARY KEY,
    token VARCHAR(50) NOT NULL UNIQUE,
    token VARCHAR(50) NOT NULL UNIQUE,
);